panic: panic condition fd < 0 occurred: Failed to open file 2.
Memory Usage: 690756 KBytes
Program aborted at tick 0
--- BEGIN LIBC BACKTRACE ---
build/X86/gem5.opt(_Z15print_backtracev+0x2c)[0x560ec40bfb5c]
build/X86/gem5.opt(_Z12abortHandleri+0x4a)[0x560ec40d267a]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f289f361980]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7)[0x7f289d180fb7]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x141)[0x7f289d182921]
build/X86/gem5.opt(+0x7a3acf)[0x560ec3ddeacf]
build/X86/gem5.opt(_ZN6Loader13ImageFileDataC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x1a79)[0x560ec3e5c0a9]
build/X86/gem5.opt(_ZN6Loader16createObjectFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEb+0x3d)[0x560ec3e5c78d]
build/X86/gem5.opt(_ZN13ProcessParams6createEv+0x4b)[0x560ec411881b]
build/X86/gem5.opt(+0x172bbd3)[0x560ec4d66bd3]
build/X86/gem5.opt(+0xa52fd9)[0x560ec408dfd9]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyCFunction_FastCallDict+0x20a)[0x7f289f78158a]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17bec8)[0x7f289f6e9ec8]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803)[0x7f289f6e8803]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be)[0x7f289f6ea2be]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803)[0x7f289f6e8803]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be)[0x7f289f6ea2be]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17ba0f)[0x7f289f6e9a0f]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c0fc)[0x7f289f6ea0fc]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803)[0x7f289f6e8803]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be)[0x7f289f6ea2be]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803)[0x7f289f6e8803]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be)[0x7f289f6ea2be]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17a803)[0x7f289f6e8803]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(+0x17c2be)[0x7f289f6ea2be]
/usr/lib/x86_64-linux-gnu/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x4ec3)[0x7f289f6f0303]
--- END LIBC BACKTRACE ---
